spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:  defaulZone:http://localhost:8761/eureka
  instance:
    hostname: localhost
